DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
BACKGROUND = (29, 38, 53)
FOREGROUND = (58, 76, 106)
INPUT_BOX_W = DISPLAY_WIDTH - (DISPLAY_WIDTH / 40)
INPUT_BOX_H = (DISPLAY_HEIGHT / 4) - 10
DISPLAY_BOX_W = DISPLAY_WIDTH - (DISPLAY_WIDTH / 40)
DISPLAY_BOX_H = DISPLAY_HEIGHT - INPUT_BOX_H + 10